name: Build binaries
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker pull clux/muslrust:stable
          docker run -v $PWD:/volume --rm -t clux/muslrust:stable cargo build --release --workspace
      - uses: actions/upload-artifact@v4
        with:
          name: typst-bot-bin
          path: |
            target/x86_64-unknown-linux-musl/release/worker
            target/x86_64-unknown-linux-musl/release/typst-bot
          compression-level: 0
