name: Build binaries
on:
  push:
    branches: [alpine]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: musl-tools
          version: 1.0.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          profile: minimal
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release --locked --workspace --target x86_64-unknown-linux-musl
      - uses: actions/upload-artifact@v4
        with:
          name: typst-bot-bin
          path: |
            target/x86_64-unknown-linux-musl/release/worker
            target/x86_64-unknown-linux-musl/release/typst-bot
          compression-level: 0
